// AUTH MODULE
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const REMEMBER_PASSWORD = 'REMEMBER_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';

// TEAMS MODULE
export const FETCH_TEAMS = 'FETCH_TEAMS';
export const FETCH_TEAM = 'FETCH_TEAM';

// PLAYERS MODULE
export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const FETCH_PLAYER = 'FETCH_PLAYERS';
